import { promises as fs } from 'fs';
import path from 'path';

const SKILLS_DIR = path.resolve('./skills');

class SkillsManager {
  constructor() {
    this.skills = new Map(); // name -> skill definition { name, description, execute }
    this.initialized = false;
  }

  async init() {
    if (this.initialized) return;
    
    try {
      // Ensure the skills directory exists
      await fs.mkdir(SKILLS_DIR, { recursive: true });
      await this.loadSkills();
      this.initialized = true;
      console.log(`SkillsManager initialized. Loaded ${this.skills.size} skills.`);
    } catch (error) {
      console.error('Failed to initialize SkillsManager:', error);
    }
  }

  async loadSkills() {
    this.skills.clear();
    try {
      const files = await fs.readdir(SKILLS_DIR);
      for (const file of files) {
        if (file.endsWith('.js')) {
          const filePath = path.join(SKILLS_DIR, file);
          try {
            // Dynamic import requires file:// scheme on Windows
            const fileUrl = new URL(`file://${filePath}`);
            const skillModule = await import(fileUrl.href);
            
            if (skillModule.name && skillModule.description && typeof skillModule.execute === 'function') {
              this.skills.set(skillModule.name, {
                name: skillModule.name,
                description: skillModule.description,
                execute: skillModule.execute
              });
              console.log(`Loaded skill: "${skillModule.name}" - ${skillModule.description}`);
            } else {
              console.warn(`Skipping invalid skill module: ${file}. Must export name, description, and execute function.`);
            }
          } catch (importErr) {
            console.error(`Error importing skill ${file}:`, importErr);
          }
        }
      }
    } catch (error) {
      console.error('Error reading skills directory:', error);
    }
  }

  getSkillsList() {
    return Array.from(this.skills.values()).map(s => ({
      name: s.name,
      description: s.description
    }));
  }

  getSkillsSystemPrompt() {
    const list = this.getSkillsList();
    if (list.length === 0) return 'No custom skills learned yet.';
    
    return list.map(s => `- Skill: "${s.name}"\n  Description: ${s.description}`).join('\n');
  }

  async learnSkill(name, description, code) {
    await this.init();
    
    // Simple sanitization of the name for filename
    const safeName = name.replace(/[^a-zA-Z0-9_]/g, '');
    const filename = `${safeName}.js`;
    const filePath = path.join(SKILLS_DIR, filename);

    console.log(`[Skills] Writing new skill "${name}" to ${filePath}...`);

    // Format the skill module code
    const formattedCode = `// Autogenerated Skill: ${name}
// Description: ${description}

export const name = ${JSON.stringify(name)};
export const description = ${JSON.stringify(description)};

export async function execute(args) {
${code}
}
`;

    try {
      await fs.writeFile(filePath, formattedCode, 'utf-8');
      
      // Load the skill to verify and register it
      const fileUrl = new URL(`file://${filePath}`);
      const skillModule = await import(fileUrl.href + `?update=${Date.now()}`); // cache busting query
      
      if (skillModule.name && skillModule.description && typeof skillModule.execute === 'function') {
        this.skills.set(skillModule.name, {
          name: skillModule.name,
          description: skillModule.description,
          execute: skillModule.execute
        });
        console.log(`[Skills] Successfully learned and registered skill: "${name}"`);
        return { success: true, message: `Skill "${name}" learned successfully.` };
      } else {
        throw new Error('Skill module format is invalid.');
      }
    } catch (error) {
      console.error(`[Skills] Failed to learn skill "${name}":`, error);
      // Clean up the invalid file if it exists
      try {
        await fs.unlink(filePath);
      } catch (_) {}
      return { success: false, error: error.message };
    }
  }

  async executeSkill(name, args) {
    await this.init();
    const skill = this.skills.get(name);
    if (!skill) {
      throw new Error(`Skill "${name}" is not loaded or does not exist.`);
    }

    console.log(`[Skills] Executing skill "${name}" with args:`, args);
    try {
      const result = await skill.execute(args);
      return result;
    } catch (error) {
      console.error(`Error executing skill "${name}":`, error);
      throw error;
    }
  }
}

export const skillsManager = new SkillsManager();
export default skillsManager;
